pipeline {
    agent any

    tools {
        maven 'maven 3.9.8'
    }

    stages {
        stage('build') {
            steps {
                echo 'compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            steps {
                echo 'Running Unit Tests on worker app'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            steps {
                echo 'Packaging worker app'
                dir('worker') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
    }
    post {
        always{
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo 'Building multibranch pipeline for worker app is completed.'
        }
    }
}
